// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyI0LcDLro4w0td1teQHJ6T5jslMi1Xtk',
    appId: '1:650298688266:web:9ef949601cd910286ab0f3',
    messagingSenderId: '650298688266',
    projectId: 'chicken-nugget-clicker-acff2',
    authDomain: 'chicken-nugget-clicker-acff2.firebaseapp.com',
    storageBucket: 'chicken-nugget-clicker-acff2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4W80Wv0UAe-5qYG4USc4R5MR3P9jMBiw',
    appId: '1:650298688266:android:a55b3248d6cd50d66ab0f3',
    messagingSenderId: '650298688266',
    projectId: 'chicken-nugget-clicker-acff2',
    storageBucket: 'chicken-nugget-clicker-acff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3mQ47FBIKn1TuA5XRUFtugz3BJYy08I',
    appId: '1:650298688266:ios:051b584d86eb94d86ab0f3',
    messagingSenderId: '650298688266',
    projectId: 'chicken-nugget-clicker-acff2',
    storageBucket: 'chicken-nugget-clicker-acff2.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3mQ47FBIKn1TuA5XRUFtugz3BJYy08I',
    appId: '1:650298688266:ios:051b584d86eb94d86ab0f3',
    messagingSenderId: '650298688266',
    projectId: 'chicken-nugget-clicker-acff2',
    storageBucket: 'chicken-nugget-clicker-acff2.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
